### ISSUE TITLE
Add hyperbolic functions

### ISSUE THREAD

**Issue by fintarin** [fintarin/Fintamath#107]

**Comment by fintarin** [comment]
Done

**Comment by artrayme** [comment]
Any updates?

**Comment by fintarin** [comment]
This task is done https://github.com/fintarin/Fintamath/tree/master/include/fintamath/functions/hyperbolic

**Comment by artrayme** [comment]
What for?

**Comment by fintarin** [comment]
Just for fun

**Comment by artrayme** [comment]
Funny hyperbolic functions 😂😂😂😂😂😂😂😂
