### ISSUE TITLE
Здравствуйте, nice to meat you

### ISSUE THREAD

**Issue by Taramin** [fintarin/Fintamath#43]
ЗДРАВСТВУЙТЕ! Хотела сказать спасибо за вашу прекрасную записную книжку, мне очень нравится, можно тут писать всякие штучки, чтобы не забыть, назначать важные встречи и даже зранить секретную информацию, ведь все равно никто не зайдет и не посмотрит! НО недавно столкнулась с одной неприятной вещью, я записала что-то очень важное, но оно удалилось! короче  говно записная книжка ваша и кринж ужасная, удалите её и перепишите и сервера в космос отправьте, чтобы не удалялось

**Comment by fintarin** [comment]
АХАХАХАХ

**Comment by artrayme** [comment]
Я столкнулся с похожей проблемой. Думаю, вам стоит лучше следить за репозиторием у уважать своих пользователей 
![image](https://user-images.githubusercontent.com/78550819/156669334-f5389680-d835-45e4-9519-41bd70cf54b7.png)

**Comment by fintarin** [comment]
Предложение принимается, ишью закрываю.
